/**
 * UJG Color System — Expo / React Native.
 * Copy this file into your project. React Native has no CSS custom properties, so
 * there is no stylesheet here — use these values directly in StyleSheet.create().
 * The `css` field on gradients is web-only; feed `colors` and `angle` to
 * expo-linear-gradient instead.
 *
 * Generated from ujg_color_system_v2_1.html. Values are verbatim; do not hand-edit.
 * Golden Rule — Never use more than 3 colors in a single design element.
 */

export interface UjgColor {
  /** Display name, exactly as written in the reference sheet. */
  name: string;
  /** kebab-case identifier, matching the CSS custom property suffix. */
  slug: string;
  /** The role this colour plays, as written in the reference sheet. */
  role: string;
  /** The hex used to paint the swatch. Same as values.HEX. */
  swatch: string;
  /** Every value system listed for this colour, keyed by system name. */
  values: Record<string, string>;
  /** Value systems in the order the reference sheet lists them. */
  systems: readonly string[];
  /**
   * Systems whose values are nearest physical matches, not computed.
   * Confirm against a fan deck before any print run.
   */
  approximate: readonly string[];
}

export interface UjgScheme {
  name: string;
  slug: string;
  colors: readonly string[];
  /** The colour names, as written in the reference sheet. */
  mix: string;
  /** What the reference sheet says to use it for. */
  usage: string | null;
}

export interface UjgGradient {
  name: string;
  slug: string;
  angle: string;
  colors: readonly string[];
  recipe: string | null;
  usage: string;
  /** Ready-made CSS value. Web targets only — React Native has no equivalent. */
  css: string;
}

/** The six core colours, each across ten value systems. */
export const ujgCore = [
  {
    name: "Night",
    slug: "night",
    role: "Primary Base",
    swatch: "#0A0A0A",
    values: {
      "HEX": "#0A0A0A",
      "HSB": "0°, 0%, 4%",
      "RGB": "10, 10, 10",
      "HUE": "0°",
      "CMYK": "0, 0, 0, 96",
      "LAB": "3, 0, 0",
      "RAL": "9005 Jet Black",
      "Copic": "100 Black",
      "HKS": "Process Black",
      "Prismacolor": "PC 935 Black",
    },
    systems: ["HEX", "HSB", "RGB", "HUE", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Deep Amethyst",
    slug: "deep-amethyst",
    role: "Tech & Royal",
    swatch: "#47107D",
    values: {
      "HEX": "#47107D",
      "HSB": "270°, 87%, 49%",
      "RGB": "71, 16, 125",
      "HUE": "270°",
      "CMYK": "43, 87, 0, 51",
      "LAB": "21, 46, -50",
      "RAL": "4007 Purple Violet",
      "Copic": "V09 Violet",
      "HKS": "37 N",
      "Prismacolor": "PC 931 Dark Purple",
    },
    systems: ["HEX", "HSB", "RGB", "HUE", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Sunset Ember",
    slug: "sunset-ember",
    role: "Energy & Action",
    swatch: "#D9531A",
    values: {
      "HEX": "#D9531A",
      "HSB": "18°, 88%, 85%",
      "RGB": "217, 83, 26",
      "HUE": "18°",
      "CMYK": "0, 62, 88, 15",
      "LAB": "53, 50, 56",
      "RAL": "2001 Red Orange",
      "Copic": "YR09 Chinese Orange",
      "HKS": "7 N",
      "Prismacolor": "PC 921 Pale Vermilion",
    },
    systems: ["HEX", "HSB", "RGB", "HUE", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Luminous Gold",
    slug: "luminous-gold",
    role: "Wealth & Legacy",
    swatch: "#F2B01E",
    values: {
      "HEX": "#F2B01E",
      "HSB": "41°, 88%, 95%",
      "RGB": "242, 176, 30",
      "HUE": "41°",
      "CMYK": "0, 27, 88, 5",
      "LAB": "76, 13, 75",
      "RAL": "1028 Melon Yellow",
      "Copic": "Y17 Golden Yellow",
      "HKS": "5 N",
      "Prismacolor": "PC 1003 Spanish Orange",
    },
    systems: ["HEX", "HSB", "RGB", "HUE", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Rich Forest",
    slug: "rich-forest",
    role: "Nature Core",
    swatch: "#0D5E39",
    values: {
      "HEX": "#0D5E39",
      "HSB": "153°, 86%, 37%",
      "RGB": "13, 94, 57",
      "HUE": "153°",
      "CMYK": "86, 0, 39, 63",
      "LAB": "35, -33, 15",
      "RAL": "6016 Turquoise Green",
      "Copic": "G28 Ocean Green",
      "HKS": "58 N",
      "Prismacolor": "PC 908 Dark Green",
    },
    systems: ["HEX", "HSB", "RGB", "HUE", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Platinum",
    slug: "platinum",
    role: "Neutral & Contrast",
    swatch: "#E8E6E1",
    values: {
      "HEX": "#E8E6E1",
      "HSB": "43°, 3%, 91%",
      "RGB": "232, 230, 225",
      "HUE": "43°",
      "CMYK": "0, 1, 3, 9",
      "LAB": "91, 0, 3",
      "RAL": "9003 Signal White",
      "Copic": "W-1 Warm Gray",
      "HKS": "Paper White",
      "Prismacolor": "PC 938 White",
    },
    systems: ["HEX", "HSB", "RGB", "HUE", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
] as const satisfies readonly UjgColor[];

/** Functional support colours. */
export const ujgFunctional = [
  {
    name: "Muted Platinum",
    slug: "muted-platinum",
    role: "secondary text",
    swatch: "#A8A5A0",
    values: {
      "HEX": "#A8A5A0",
      "HSB": "38°, 5%, 66%",
      "RGB": "168,165,160",
      "CMYK": "0,2,5,34",
      "LAB": "68, 0, 3",
      "RAL": "7038 Agate Grey",
    },
    systems: ["HEX", "HSB", "RGB", "CMYK", "LAB", "RAL"],
    approximate: ["RAL"],
  },
  {
    name: "Rich Jungle Green",
    slug: "rich-jungle-green",
    role: "success",
    swatch: "#2E6B4F",
    values: {
      "HEX": "#2E6B4F",
      "HSB": "152°, 57%, 42%",
      "RGB": "46,107,79",
      "CMYK": "57,0,26,58",
      "LAB": "41, -27, 10",
      "RAL": "6000 Patina Green",
    },
    systems: ["HEX", "HSB", "RGB", "CMYK", "LAB", "RAL"],
    approximate: ["RAL"],
  },
] as const satisfies readonly UjgColor[];

/** Extended palette — earth tones (secondary). */
export const ujgExtended = [
  {
    name: "Midnight Forest",
    slug: "midnight-forest",
    role: "Deepest Forest",
    swatch: "#042F1E",
    values: {
      "HEX": "#042F1E",
      "HSB": "156, 91, 18",
      "RGB": "4, 47, 30",
      "HSL": "156, 84, 10",
      "CMYK": "84, 51, 81, 68",
      "LAB": "16, -18, 7",
      "RAL": "6009 Fir Green",
      "Copic": "G99 Olive",
      "HKS": "63 N",
      "Prismacolor": "PC908 Dark Green",
    },
    systems: ["HEX", "HSB", "RGB", "HSL", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Clay Ember",
    slug: "clay-ember",
    role: "Burnt Clay",
    swatch: "#C15C27",
    values: {
      "HEX": "#C15C27",
      "HSB": "21, 80, 76",
      "RGB": "193, 92, 39",
      "HSL": "21, 66, 54",
      "CMYK": "18, 75, 100, 6",
      "LAB": "51, 39, 49",
      "RAL": "8023 Orange Brown",
      "Copic": "YR07 Cadmium Orange",
      "HKS": "8 N",
      "Prismacolor": "PC943 Burnt Ochre",
    },
    systems: ["HEX", "HSB", "RGB", "HSL", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Harvest Gold",
    slug: "harvest-gold",
    role: "Soft Amber",
    swatch: "#E1A443",
    values: {
      "HEX": "#E1A443",
      "HSB": "37, 70, 88",
      "RGB": "225, 164, 67",
      "HSL": "37, 72, 57",
      "CMYK": "11, 38, 87, 0",
      "LAB": "72, 17, 58",
      "RAL": "1024 Ochre Yellow",
      "Copic": "Y17 Golden Yellow",
      "HKS": "4 N",
      "Prismacolor": "PC942 Yellow Ochre",
    },
    systems: ["HEX", "HSB", "RGB", "HSL", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Sage",
    slug: "sage",
    role: "Herbal Neutral",
    swatch: "#587156",
    values: {
      "HEX": "#587156",
      "HSB": "116, 24, 44",
      "RGB": "88, 113, 86",
      "HSL": "116, 14, 39",
      "CMYK": "65, 39, 71, 21",
      "LAB": "45, -13, 12",
      "RAL": "6013 Reed Green",
      "Copic": "G85 Verdigris",
      "HKS": "61 N",
      "Prismacolor": "PC1090 Kelp Green",
    },
    systems: ["HEX", "HSB", "RGB", "HSL", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Marigold",
    slug: "marigold",
    role: "Warm Accent",
    swatch: "#E28D1F",
    values: {
      "HEX": "#E28D1F",
      "HSB": "34, 86, 89",
      "RGB": "226, 141, 31",
      "HSL": "34, 77, 50",
      "CMYK": "9, 51, 100, 0",
      "LAB": "67, 28, 66",
      "RAL": "2000 Yellow Orange",
      "Copic": "YR15 Pumpkin Yellow",
      "HKS": "5 N",
      "Prismacolor": "PC1003 Spanish Orange",
    },
    systems: ["HEX", "HSB", "RGB", "HSL", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Warm Sand",
    slug: "warm-sand",
    role: "Warm Light",
    swatch: "#F7DFC0",
    values: {
      "HEX": "#F7DFC0",
      "HSB": "34, 22, 97",
      "RGB": "247, 223, 192",
      "HSL": "34, 77, 86",
      "CMYK": "2, 13, 25, 0",
      "LAB": "90, 6, 19",
      "RAL": "1015 Light Ivory",
      "Copic": "E51 Milky White",
      "HKS": "84 N",
      "Prismacolor": "PC1012 Jasmine",
    },
    systems: ["HEX", "HSB", "RGB", "HSL", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
  {
    name: "Terracotta",
    slug: "terracotta",
    role: "Grounded Earth",
    swatch: "#B04720",
    values: {
      "HEX": "#B04720",
      "HSB": "16, 82, 69",
      "RGB": "176, 71, 32",
      "HSL": "16, 69, 41",
      "CMYK": "22, 84, 100, 13",
      "LAB": "45, 43, 45",
      "RAL": "8004 Copper Brown",
      "Copic": "E08 Brown",
      "HKS": "9 N",
      "Prismacolor": "PC945 Sienna Brown",
    },
    systems: ["HEX", "HSB", "RGB", "HSL", "CMYK", "LAB", "RAL", "Copic", "HKS", "Prismacolor"],
    approximate: ["RAL", "Copic", "HKS", "Prismacolor"],
  },
] as const satisfies readonly UjgColor[];

/** Every colour in the system, flat, keyed by camelCase name. */
export const ujgColors = {
  night: "#0A0A0A",
  deepAmethyst: "#47107D",
  sunsetEmber: "#D9531A",
  luminousGold: "#F2B01E",
  richForest: "#0D5E39",
  platinum: "#E8E6E1",
  mutedPlatinum: "#A8A5A0",
  richJungleGreen: "#2E6B4F",
  midnightForest: "#042F1E",
  clayEmber: "#C15C27",
  harvestGold: "#E1A443",
  sage: "#587156",
  marigold: "#E28D1F",
  warmSand: "#F7DFC0",
  terracotta: "#B04720",
} as const;

export type UjgColorName = keyof typeof ujgColors;

/** Semantic role -> colour. Straight from the Functional Mapping table. */
export const ujgRoles = {
  primary: "#0A0A0A", // Night — logos, headers
  secondary: "#47107D", // Deep Amethyst — key UI, accents
  accent: "#F2B01E", // Luminous Gold — highlights, links
  ctaAction: "#D9531A", // Sunset Ember
  neutralDark: "#0D5E39", // Rich Forest — text, borders
  neutralMid: "#A8A5A0", // Muted Platinum — secondary text
  neutralLight: "#E8E6E1", // Platinum — backgrounds
  success: "#2E6B4F", // Rich Jungle Green
  warning: "#F2B01E", // Luminous Gold
  errorUrgent: "#D9531A", // Sunset Ember
  info: "#47107D", // Deep Amethyst
} as const;

export type UjgRole = keyof typeof ujgRoles;

/** Color schemes — 20 trios. */
export const ujgTrios = [
  {
    name: "Afro-Futurist Royal",
    slug: "afro-futurist-royal",
    colors: ["#47107D", "#F2B01E", "#0A0A0A"],
    mix: "Amethyst + Gold + Night",
    usage: "flagship brand visuals, authority, decks",
  },
  {
    name: "Urban Jungle Grounded",
    slug: "urban-jungle-grounded",
    colors: ["#0D5E39", "#F2B01E", "#E8E6E1"],
    mix: "Rich Forest + Gold + Platinum",
    usage: "wellness, ancestral, eco, light collateral",
  },
  {
    name: "Sunset Rebellion",
    slug: "sunset-rebellion",
    colors: ["#D9531A", "#47107D", "#0A0A0A"],
    mix: "Ember + Amethyst + Night",
    usage: "campaigns, launches, provocation",
  },
  {
    name: "Vibranium Court",
    slug: "vibranium-court",
    colors: ["#47107D", "#E8E6E1", "#0A0A0A"],
    mix: "Amethyst + Platinum + Night",
    usage: "premium dark UI, nav bars, elegant tech surfaces",
  },
  {
    name: "Solar Harvest",
    slug: "solar-harvest",
    colors: ["#F2B01E", "#D9531A", "#0A0A0A"],
    mix: "Gold + Ember + Night",
    usage: "warm CTAs, sales pages, product warmth",
  },
  {
    name: "Emerald Circuit",
    slug: "emerald-circuit",
    colors: ["#0D5E39", "#47107D", "#0A0A0A"],
    mix: "Rich Forest + Amethyst + Night",
    usage: "spiritual tech, journaling, sacred interfaces",
  },
  {
    name: "Obsidian Gold",
    slug: "obsidian-gold",
    colors: ["#0A0A0A", "#F2B01E", "#E8E6E1"],
    mix: "Night + Gold + Platinum",
    usage: "luxe minimal, packaging, stationery, monograms",
  },
  {
    name: "Ember Ash",
    slug: "ember-ash",
    colors: ["#D9531A", "#E8E6E1", "#0A0A0A"],
    mix: "Ember + Platinum + Night",
    usage: "bold editorial, posters, social headlines",
  },
  {
    name: "Sacred Grove",
    slug: "sacred-grove",
    colors: ["#0D5E39", "#47107D", "#E8E6E1"],
    mix: "Rich Forest + Amethyst + Platinum",
    usage: "airy sacred, light wellness, ceremony collateral",
  },
  {
    name: "Molten Crown",
    slug: "molten-crown",
    colors: ["#D9531A", "#F2B01E", "#47107D"],
    mix: "Ember + Gold + Amethyst",
    usage: "rich reveal, hero art (ground on Night or Platinum)",
  },
  {
    name: "Circuit Grove",
    slug: "circuit-grove",
    colors: ["#0D5E39", "#D9531A", "#0A0A0A"],
    mix: "Rich Forest + Ember + Night",
    usage: "eco-action campaigns, product",
  },
  {
    name: "Forest Signal",
    slug: "forest-signal",
    colors: ["#0D5E39", "#F2B01E", "#0A0A0A"],
    mix: "Rich Forest + Gold + Night",
    usage: "wellness authority on dark",
  },
  {
    name: "Deep Canopy",
    slug: "deep-canopy",
    colors: ["#0D5E39", "#E8E6E1", "#0A0A0A"],
    mix: "Rich Forest + Platinum + Night",
    usage: "calm reports, docs",
  },
  {
    name: "Royal Grove",
    slug: "royal-grove",
    colors: ["#47107D", "#0D5E39", "#F2B01E"],
    mix: "Amethyst + Rich Forest + Gold",
    usage: "three-jewel hero (ground on Night or Platinum)",
  },
  {
    name: "Amethyst Signal",
    slug: "amethyst-signal",
    colors: ["#47107D", "#F2B01E", "#E8E6E1"],
    mix: "Amethyst + Gold + Platinum",
    usage: "premium light decks, one-pagers",
  },
  {
    name: "Vibrant Jungle",
    slug: "vibrant-jungle",
    colors: ["#47107D", "#D9531A", "#0D5E39"],
    mix: "Amethyst + Ember + Rich Forest",
    usage: "bold multi-jewel (ground on Night)",
  },
  {
    name: "Cosmic Ember",
    slug: "cosmic-ember",
    colors: ["#47107D", "#D9531A", "#E8E6E1"],
    mix: "Amethyst + Ember + Platinum",
    usage: "energetic premium light",
  },
  {
    name: "Harvest Fire",
    slug: "harvest-fire",
    colors: ["#D9531A", "#F2B01E", "#0D5E39"],
    mix: "Ember + Gold + Rich Forest",
    usage: "food, eco, abundance campaigns",
  },
  {
    name: "Solar Flare",
    slug: "solar-flare",
    colors: ["#D9531A", "#F2B01E", "#E8E6E1"],
    mix: "Ember + Gold + Platinum",
    usage: "bright warm light, launches",
  },
  {
    name: "Ember Meadow",
    slug: "ember-meadow",
    colors: ["#D9531A", "#0D5E39", "#E8E6E1"],
    mix: "Ember + Rich Forest + Platinum",
    usage: "warm on green, wellness",
  },
] as const satisfies readonly UjgScheme[];

/** Gradients — 20. */
export const ujgGradients = [
  {
    name: "Quantum Royalty",
    slug: "quantum-royalty",
    angle: "135deg",
    colors: ["#47107D", "#F2B01E", "#E8E6E1"],
    recipe: "Amethyst → Gold → Platinum",
    usage: "Digital banners, hero UI, profile frames",
    css: "linear-gradient(135deg,#47107D,#F2B01E,#E8E6E1)",
  },
  {
    name: "Jungle Pulse",
    slug: "jungle-pulse",
    angle: "135deg",
    colors: ["#0D5E39", "#D9531A", "#0A0A0A"],
    recipe: "Rich Forest → Ember → Night",
    usage: "Dashboards, presentations, reports",
    css: "linear-gradient(135deg,#0D5E39,#D9531A,#0A0A0A)",
  },
  {
    name: "Vibranium Heat",
    slug: "vibranium-heat",
    angle: "135deg",
    colors: ["#D9531A", "#47107D", "#0A0A0A"],
    recipe: "Ember → Amethyst → Night",
    usage: "Motion graphics, glitch effects, banners",
    css: "linear-gradient(135deg,#D9531A,#47107D,#0A0A0A)",
  },
  {
    name: "Solar Echo",
    slug: "solar-echo",
    angle: "135deg",
    colors: ["#F2B01E", "#E8E6E1", "#0D5E39"],
    recipe: "Gold → Platinum → Rich Forest",
    usage: "Onboarding flows, learning content",
    css: "linear-gradient(135deg,#F2B01E,#E8E6E1,#0D5E39)",
  },
  {
    name: "Ancestral Interface",
    slug: "ancestral-interface",
    angle: "135deg",
    colors: ["#0A0A0A", "#E8E6E1", "#47107D"],
    recipe: "Night → Platinum → Amethyst",
    usage: "Scroll transitions, footers",
    css: "linear-gradient(135deg,#0A0A0A,#E8E6E1,#47107D)",
  },
  {
    name: "Cyber Mirage",
    slug: "cyber-mirage",
    angle: "135deg",
    colors: ["#47107D", "#E8E6E1", "#D9531A"],
    recipe: "Amethyst → Platinum → Ember",
    usage: "Hero UI, app transitions",
    css: "linear-gradient(135deg,#47107D,#E8E6E1,#D9531A)",
  },
  {
    name: "Obsidian Bloom",
    slug: "obsidian-bloom",
    angle: "135deg",
    colors: ["#0A0A0A", "#0D5E39", "#F2B01E"],
    recipe: "Night → Rich Forest → Gold",
    usage: "Finance tools, storytelling sliders",
    css: "linear-gradient(135deg,#0A0A0A,#0D5E39,#F2B01E)",
  },
  {
    name: "Panther Pulse",
    slug: "panther-pulse",
    angle: "135deg",
    colors: ["#D9531A", "#F2B01E", "#47107D"],
    recipe: "Ember → Gold → Amethyst",
    usage: "Product reveals, CTA banners",
    css: "linear-gradient(135deg,#D9531A,#F2B01E,#47107D)",
  },
  {
    name: "Electric Clay",
    slug: "electric-clay",
    angle: "135deg",
    colors: ["#F2B01E", "#D9531A", "#E8E6E1"],
    recipe: "Gold → Ember → Platinum",
    usage: "Minimal UI, eBooks, merch packaging",
    css: "linear-gradient(135deg,#F2B01E,#D9531A,#E8E6E1)",
  },
  {
    name: "Sacred Transmission",
    slug: "sacred-transmission",
    angle: "135deg",
    colors: ["#0D5E39", "#47107D", "#0A0A0A"],
    recipe: "Rich Forest → Amethyst → Night",
    usage: "Spiritual tech interfaces, journaling",
    css: "linear-gradient(135deg,#0D5E39,#47107D,#0A0A0A)",
  },
  {
    name: "Nightfall Gold",
    slug: "nightfall-gold",
    angle: "135deg",
    colors: ["#0A0A0A", "#47107D", "#F2B01E"],
    recipe: "Night → Amethyst → Gold",
    usage: "Footers, hero",
    css: "linear-gradient(135deg,#0A0A0A,#47107D,#F2B01E)",
  },
  {
    name: "Emerald Dawn",
    slug: "emerald-dawn",
    angle: "135deg",
    colors: ["#0D5E39", "#F2B01E", "#E8E6E1"],
    recipe: "Rich Forest → Gold → Platinum",
    usage: "Onboarding, light content",
    css: "linear-gradient(135deg,#0D5E39,#F2B01E,#E8E6E1)",
  },
  {
    name: "Violet Sun",
    slug: "violet-sun",
    angle: "135deg",
    colors: ["#47107D", "#D9531A", "#F2B01E"],
    recipe: "Amethyst → Ember → Gold",
    usage: "Campaigns, motion",
    css: "linear-gradient(135deg,#47107D,#D9531A,#F2B01E)",
  },
  {
    name: "Deep Current",
    slug: "deep-current",
    angle: "135deg",
    colors: ["#0A0A0A", "#0D5E39", "#E8E6E1"],
    recipe: "Night → Rich Forest → Platinum",
    usage: "Calm backgrounds",
    css: "linear-gradient(135deg,#0A0A0A,#0D5E39,#E8E6E1)",
  },
  {
    name: "Royal Ash",
    slug: "royal-ash",
    angle: "135deg",
    colors: ["#47107D", "#A8A5A0", "#0A0A0A"],
    recipe: "Amethyst → Muted Platinum → Night",
    usage: "UI depth, panels",
    css: "linear-gradient(135deg,#47107D,#A8A5A0,#0A0A0A)",
  },
  {
    name: "Ember Veil",
    slug: "ember-veil",
    angle: "135deg",
    colors: ["#D9531A", "#47107D", "#E8E6E1"],
    recipe: "Ember → Amethyst → Platinum",
    usage: "Banners",
    css: "linear-gradient(135deg,#D9531A,#47107D,#E8E6E1)",
  },
  {
    name: "Goldstream",
    slug: "goldstream",
    angle: "135deg",
    colors: ["#F2B01E", "#0D5E39", "#0A0A0A"],
    recipe: "Gold → Rich Forest → Night",
    usage: "Reports, finance",
    css: "linear-gradient(135deg,#F2B01E,#0D5E39,#0A0A0A)",
  },
  {
    name: "Platinum Rise",
    slug: "platinum-rise",
    angle: "135deg",
    colors: ["#0A0A0A", "#47107D", "#E8E6E1"],
    recipe: "Night → Amethyst → Platinum",
    usage: "Scroll transitions",
    css: "linear-gradient(135deg,#0A0A0A,#47107D,#E8E6E1)",
  },
  {
    name: "Forest Flare",
    slug: "forest-flare",
    angle: "135deg",
    colors: ["#0D5E39", "#D9531A", "#F2B01E"],
    recipe: "Rich Forest → Ember → Gold",
    usage: "Product reveals",
    css: "linear-gradient(135deg,#0D5E39,#D9531A,#F2B01E)",
  },
  {
    name: "Molten Night",
    slug: "molten-night",
    angle: "135deg",
    colors: ["#0A0A0A", "#D9531A", "#47107D"],
    recipe: "Night → Ember → Amethyst",
    usage: "Motion graphics",
    css: "linear-gradient(135deg,#0A0A0A,#D9531A,#47107D)",
  },
] as const satisfies readonly UjgGradient[];

/** Mood palettes — 20. Four seasons plus sixteen registers. */
export const ujgMoods = [
  {
    name: "Spring",
    slug: "spring",
    colors: ["#E8E6E1", "#F2B01E", "#0D5E39", "#47107D"],
    mix: "Platinum · Gold · Rich Forest · Amethyst",
    usage: "clean, fertile, new systems waking",
  },
  {
    name: "Summer",
    slug: "summer",
    colors: ["#D9531A", "#F2B01E", "#47107D", "#0A0A0A"],
    mix: "Ember · Gold · Amethyst · Night",
    usage: "magnetic, celebratory, high energy",
  },
  {
    name: "Fall",
    slug: "fall",
    colors: ["#D9531A", "#0D5E39", "#F2B01E", "#47107D"],
    mix: "Ember · Rich Forest · Gold · Amethyst",
    usage: "legacy building, deep strategy",
  },
  {
    name: "Winter",
    slug: "winter",
    colors: ["#0A0A0A", "#E8E6E1", "#0D5E39", "#47107D"],
    mix: "Night · Platinum · Rich Forest · Amethyst",
    usage: "sacred silence, encrypted memory",
  },
  {
    name: "Sovereign",
    slug: "sovereign",
    colors: ["#0A0A0A", "#47107D", "#F2B01E", "#E8E6E1"],
    mix: "Night · Amethyst · Gold · Platinum",
    usage: null,
  },
  {
    name: "Grounded",
    slug: "grounded",
    colors: ["#042F1E", "#587156", "#F7DFC0", "#0D5E39"],
    mix: "Midnight Forest · Sage · Warm Sand · Rich Forest",
    usage: null,
  },
  {
    name: "Rebellious",
    slug: "rebellious",
    colors: ["#0A0A0A", "#D9531A", "#47107D", "#A8A5A0"],
    mix: "Night · Ember · Amethyst · Muted Platinum",
    usage: null,
  },
  {
    name: "Sacred",
    slug: "sacred",
    colors: ["#042F1E", "#47107D", "#E1A443", "#F7DFC0"],
    mix: "Midnight Forest · Amethyst · Harvest Gold · Warm Sand",
    usage: null,
  },
  {
    name: "Luxe",
    slug: "luxe",
    colors: ["#0A0A0A", "#F2B01E", "#B04720", "#E8E6E1"],
    mix: "Night · Gold · Terracotta · Platinum",
    usage: null,
  },
  {
    name: "Electric",
    slug: "electric",
    colors: ["#47107D", "#D9531A", "#F2B01E", "#0A0A0A"],
    mix: "Amethyst · Ember · Gold · Night",
    usage: null,
  },
  {
    name: "Tender",
    slug: "tender",
    colors: ["#F7DFC0", "#E1A443", "#587156", "#E8E6E1"],
    mix: "Warm Sand · Harvest Gold · Sage · Platinum",
    usage: null,
  },
  {
    name: "Mystic",
    slug: "mystic",
    colors: ["#0A0A0A", "#47107D", "#042F1E", "#A8A5A0"],
    mix: "Night · Amethyst · Midnight Forest · Muted Platinum",
    usage: null,
  },
  {
    name: "Warm",
    slug: "warm",
    colors: ["#E1A443", "#C15C27", "#F7DFC0", "#0D5E39"],
    mix: "Harvest Gold · Clay Ember · Warm Sand · Rich Forest",
    usage: null,
  },
  {
    name: "Focused",
    slug: "focused",
    colors: ["#0A0A0A", "#47107D", "#E8E6E1", "#A8A5A0"],
    mix: "Night · Amethyst · Platinum · Muted Platinum",
    usage: null,
  },
  {
    name: "Celebratory",
    slug: "celebratory",
    colors: ["#D9531A", "#E28D1F", "#F2B01E", "#47107D"],
    mix: "Ember · Marigold · Gold · Amethyst",
    usage: null,
  },
  {
    name: "Healing",
    slug: "healing",
    colors: ["#587156", "#0D5E39", "#F7DFC0", "#E1A443"],
    mix: "Sage · Rich Forest · Warm Sand · Harvest Gold",
    usage: null,
  },
  {
    name: "Bold",
    slug: "bold",
    colors: ["#D9531A", "#B04720", "#0A0A0A", "#F2B01E"],
    mix: "Ember · Terracotta · Night · Gold",
    usage: null,
  },
  {
    name: "Serene",
    slug: "serene",
    colors: ["#042F1E", "#587156", "#E8E6E1", "#A8A5A0"],
    mix: "Midnight Forest · Sage · Platinum · Muted Platinum",
    usage: null,
  },
  {
    name: "Regal",
    slug: "regal",
    colors: ["#47107D", "#F2B01E", "#B04720", "#0A0A0A"],
    mix: "Amethyst · Gold · Terracotta · Night",
    usage: null,
  },
  {
    name: "Dawn",
    slug: "dawn",
    colors: ["#F7DFC0", "#E1A443", "#0D5E39", "#47107D"],
    mix: "Warm Sand · Harvest Gold · Rich Forest · Amethyst",
    usage: null,
  },
] as const satisfies readonly UjgScheme[];

/** Tech + Earth gradients — 20. */
export const ujgTechEarthGradients = [
  {
    name: "Vibranium Clay",
    slug: "vibranium-clay",
    angle: "135deg",
    colors: ["#47107D", "#B04720", "#0A0A0A"],
    recipe: "Deep Amethyst → Terracotta → Night",
    usage: "Royal tech grounded in earth — hero, packaging",
    css: "linear-gradient(135deg,#47107D,#B04720,#0A0A0A)",
  },
  {
    name: "Circuit Harvest",
    slug: "circuit-harvest",
    angle: "135deg",
    colors: ["#0D5E39", "#E1A443", "#F7DFC0"],
    recipe: "Rich Forest → Harvest Gold → Warm Sand",
    usage: "Tech-green into organic light — onboarding, wellness",
    css: "linear-gradient(135deg,#0D5E39,#E1A443,#F7DFC0)",
  },
  {
    name: "Amethyst Ember",
    slug: "amethyst-ember",
    angle: "135deg",
    colors: ["#47107D", "#C15C27", "#E28D1F"],
    recipe: "Deep Amethyst → Clay Ember → Marigold",
    usage: "Purple to warm clay — campaigns, motion",
    css: "linear-gradient(135deg,#47107D,#C15C27,#E28D1F)",
  },
  {
    name: "Solar Loam",
    slug: "solar-loam",
    angle: "135deg",
    colors: ["#F2B01E", "#E28D1F", "#B04720"],
    recipe: "Luminous Gold → Marigold → Terracotta",
    usage: "Gold cascading into earth — product reveals",
    css: "linear-gradient(135deg,#F2B01E,#E28D1F,#B04720)",
  },
  {
    name: "Sacred Canopy",
    slug: "sacred-canopy",
    angle: "135deg",
    colors: ["#042F1E", "#0D5E39", "#587156"],
    recipe: "Midnight Forest → Rich Forest → Sage",
    usage: "Deep to living to soft green — journaling, spiritual",
    css: "linear-gradient(135deg,#042F1E,#0D5E39,#587156)",
  },
  {
    name: "Obsidian Terracotta",
    slug: "obsidian-terracotta",
    angle: "135deg",
    colors: ["#0A0A0A", "#B04720", "#F7DFC0"],
    recipe: "Night → Terracotta → Warm Sand",
    usage: "Dark to clay to sand — editorial, print",
    css: "linear-gradient(135deg,#0A0A0A,#B04720,#F7DFC0)",
  },
  {
    name: "Neon Sage",
    slug: "neon-sage",
    angle: "135deg",
    colors: ["#47107D", "#587156", "#F7DFC0"],
    recipe: "Deep Amethyst → Sage → Warm Sand",
    usage: "Tech to herbal to light — calm UI, learning",
    css: "linear-gradient(135deg,#47107D,#587156,#F7DFC0)",
  },
  {
    name: "Ember Dusk",
    slug: "ember-dusk",
    angle: "135deg",
    colors: ["#D9531A", "#C15C27", "#042F1E"],
    recipe: "Sunset Ember → Clay Ember → Midnight Forest",
    usage: "Warm into deep green — banners, seasonal",
    css: "linear-gradient(135deg,#D9531A,#C15C27,#042F1E)",
  },
  {
    name: "Clay Dawn",
    slug: "clay-dawn",
    angle: "135deg",
    colors: ["#B04720", "#E1A443", "#F7DFC0"],
    recipe: "Terracotta → Harvest Gold → Warm Sand",
    usage: "Terracotta rising into light — morning, wellness",
    css: "linear-gradient(135deg,#B04720,#E1A443,#F7DFC0)",
  },
  {
    name: "Jungle Gilt",
    slug: "jungle-gilt",
    angle: "135deg",
    colors: ["#0D5E39", "#F2B01E", "#0A0A0A"],
    recipe: "Rich Forest → Luminous Gold → Night",
    usage: "Living green to gold on dark — luxe eco hero",
    css: "linear-gradient(135deg,#0D5E39,#F2B01E,#0A0A0A)",
  },
  {
    name: "Royal Harvest",
    slug: "royal-harvest",
    angle: "135deg",
    colors: ["#47107D", "#F2B01E", "#E1A443"],
    recipe: "Deep Amethyst → Gold → Harvest Gold",
    usage: "Amethyst into amber warmth — premium reveal",
    css: "linear-gradient(135deg,#47107D,#F2B01E,#E1A443)",
  },
  {
    name: "Sage Circuit",
    slug: "sage-circuit",
    angle: "135deg",
    colors: ["#587156", "#0D5E39", "#47107D"],
    recipe: "Sage → Rich Forest → Deep Amethyst",
    usage: "Herbal green into tech — calm learning UI",
    css: "linear-gradient(135deg,#587156,#0D5E39,#47107D)",
  },
  {
    name: "Marigold Forest",
    slug: "marigold-forest",
    angle: "135deg",
    colors: ["#E28D1F", "#0D5E39", "#042F1E"],
    recipe: "Marigold → Rich Forest → Midnight Forest",
    usage: "Warm bloom into deep canopy — seasonal, botanical",
    css: "linear-gradient(135deg,#E28D1F,#0D5E39,#042F1E)",
  },
  {
    name: "Terra Royal",
    slug: "terra-royal",
    angle: "135deg",
    colors: ["#B04720", "#47107D", "#0A0A0A"],
    recipe: "Terracotta → Deep Amethyst → Night",
    usage: "Clay into royal shadow — editorial, ancestral",
    css: "linear-gradient(135deg,#B04720,#47107D,#0A0A0A)",
  },
  {
    name: "Ember Sand",
    slug: "ember-sand",
    angle: "135deg",
    colors: ["#D9531A", "#B04720", "#F7DFC0"],
    recipe: "Sunset Ember → Terracotta → Warm Sand",
    usage: "Molten warmth cooling to sand — packaging, print",
    css: "linear-gradient(135deg,#D9531A,#B04720,#F7DFC0)",
  },
  {
    name: "Gold Loam",
    slug: "gold-loam",
    angle: "135deg",
    colors: ["#F2B01E", "#587156", "#042F1E"],
    recipe: "Luminous Gold → Sage → Midnight Forest",
    usage: "Gold settling into soil — abundance, grounded",
    css: "linear-gradient(135deg,#F2B01E,#587156,#042F1E)",
  },
  {
    name: "Deep Sage",
    slug: "deep-sage",
    angle: "135deg",
    colors: ["#042F1E", "#587156", "#E1A443"],
    recipe: "Midnight Forest → Sage → Harvest Gold",
    usage: "Dark canopy lifting to amber — journaling, meditation",
    css: "linear-gradient(135deg,#042F1E,#587156,#E1A443)",
  },
  {
    name: "Clay Amethyst",
    slug: "clay-amethyst",
    angle: "135deg",
    colors: ["#47107D", "#B04720", "#E1A443"],
    recipe: "Deep Amethyst → Terracotta → Harvest Gold",
    usage: "Royal warmed by earth — hero, brand primary",
    css: "linear-gradient(135deg,#47107D,#B04720,#E1A443)",
  },
  {
    name: "Harvest Night",
    slug: "harvest-night",
    angle: "135deg",
    colors: ["#E1A443", "#B04720", "#0A0A0A"],
    recipe: "Harvest Gold → Terracotta → Night",
    usage: "Amber into clay into dark — luxe, moody",
    css: "linear-gradient(135deg,#E1A443,#B04720,#0A0A0A)",
  },
  {
    name: "Warm Vibranium",
    slug: "warm-vibranium",
    angle: "135deg",
    colors: ["#47107D", "#0D5E39", "#F2B01E"],
    recipe: "Deep Amethyst → Rich Forest → Luminous Gold",
    usage: "Tech royal through jungle to gold — signature blend",
    css: "linear-gradient(135deg,#47107D,#0D5E39,#F2B01E)",
  },
] as const satisfies readonly UjgGradient[];

/** Tech + Earth schemes — 20 trios. */
export const ujgTechEarthTrios = [
  {
    name: "Rooted Sovereign",
    slug: "rooted-sovereign",
    colors: ["#47107D", "#E1A443", "#F7DFC0"],
    mix: "Amethyst + Harvest Gold + Warm Sand",
    usage: "premium organic",
  },
  {
    name: "Jungle Circuit",
    slug: "jungle-circuit",
    colors: ["#0D5E39", "#587156", "#F2B01E"],
    mix: "Rich Forest + Sage + Gold",
    usage: "tech-nature wellness",
  },
  {
    name: "Clay Court",
    slug: "clay-court",
    colors: ["#0A0A0A", "#B04720", "#F7DFC0"],
    mix: "Night + Terracotta + Warm Sand",
    usage: "grounded luxe",
  },
  {
    name: "Ember Grove",
    slug: "ember-grove",
    colors: ["#D9531A", "#042F1E", "#F7DFC0"],
    mix: "Sunset Ember + Midnight Forest + Warm Sand",
    usage: "warm on deep green",
  },
  {
    name: "Amethyst Earth",
    slug: "amethyst-earth",
    colors: ["#47107D", "#B04720", "#587156"],
    mix: "Amethyst + Terracotta + Sage",
    usage: "royal meets soil",
  },
  {
    name: "Harvest Tech",
    slug: "harvest-tech",
    colors: ["#F2B01E", "#0D5E39", "#C15C27"],
    mix: "Gold + Rich Forest + Clay Ember",
    usage: "abundance",
  },
  {
    name: "Sacred Sand",
    slug: "sacred-sand",
    colors: ["#042F1E", "#E28D1F", "#F7DFC0"],
    mix: "Midnight Forest + Marigold + Warm Sand",
    usage: "ceremonial",
  },
  {
    name: "Panther Clay",
    slug: "panther-clay",
    colors: ["#0A0A0A", "#C15C27", "#A8A5A0"],
    mix: "Night + Clay Ember + Muted Platinum",
    usage: "editorial earth",
  },
  {
    name: "Obsidian Sage",
    slug: "obsidian-sage",
    colors: ["#0A0A0A", "#587156", "#E1A443"],
    mix: "Night + Sage + Harvest Gold",
    usage: "calm premium, wellness-tech",
  },
  {
    name: "Amethyst Clay",
    slug: "amethyst-clay",
    colors: ["#47107D", "#C15C27", "#F7DFC0"],
    mix: "Amethyst + Clay Ember + Warm Sand",
    usage: "royal warmth, packaging",
  },
  {
    name: "Gilded Forest",
    slug: "gilded-forest",
    colors: ["#F2B01E", "#042F1E", "#F7DFC0"],
    mix: "Gold + Midnight Forest + Warm Sand",
    usage: "luxe eco, foil on deep green",
  },
  {
    name: "Ember Terra",
    slug: "ember-terra",
    colors: ["#D9531A", "#B04720", "#0A0A0A"],
    mix: "Sunset Ember + Terracotta + Night",
    usage: "molten earth, bold campaigns",
  },
  {
    name: "Circuit Sand",
    slug: "circuit-sand",
    colors: ["#47107D", "#587156", "#F7DFC0"],
    mix: "Amethyst + Sage + Warm Sand",
    usage: "soft tech, learning, UI",
  },
  {
    name: "Marigold Night",
    slug: "marigold-night",
    colors: ["#0A0A0A", "#E28D1F", "#E8E6E1"],
    mix: "Night + Marigold + Platinum",
    usage: "festive pop on dark, social",
  },
  {
    name: "Rooted Amethyst",
    slug: "rooted-amethyst",
    colors: ["#0D5E39", "#47107D", "#E1A443"],
    mix: "Rich Forest + Amethyst + Harvest Gold",
    usage: "jungle-tech-gold hero",
  },
  {
    name: "Terra Circuit",
    slug: "terra-circuit",
    colors: ["#47107D", "#E28D1F", "#042F1E"],
    mix: "Amethyst + Marigold + Midnight Forest",
    usage: "royal warmth on deep green",
  },
  {
    name: "Golden Grove",
    slug: "golden-grove",
    colors: ["#F2B01E", "#587156", "#042F1E"],
    mix: "Gold + Sage + Midnight Forest",
    usage: "gilded botanical",
  },
  {
    name: "Sunfire Clay",
    slug: "sunfire-clay",
    colors: ["#D9531A", "#E28D1F", "#C15C27"],
    mix: "Ember + Marigold + Clay Ember",
    usage: "all-warm heat (ground on Night)",
  },
  {
    name: "Amethyst Sand",
    slug: "amethyst-sand",
    colors: ["#47107D", "#E1A443", "#587156"],
    mix: "Amethyst + Harvest Gold + Sage",
    usage: "royal, amber, herbal",
  },
  {
    name: "Forest Ember",
    slug: "forest-ember",
    colors: ["#0D5E39", "#C15C27", "#F7DFC0"],
    mix: "Rich Forest + Clay Ember + Warm Sand",
    usage: "jungle clay",
  },
] as const satisfies readonly UjgScheme[];

/** Themed palettes (Tech + Earth) — 20. */
export const ujgThemed = [
  {
    name: "Amazonia",
    slug: "amazonia",
    colors: ["#042F1E", "#0D5E39", "#587156", "#E1A443", "#B04720", "#F7DFC0"],
    mix: "Midnight Forest · Rich Forest · Sage · Harvest Gold · Terracotta · Warm Sand",
    usage: "wellness, ancestral, Amazonia persona",
  },
  {
    name: "Command Core",
    slug: "command-core",
    colors: ["#0A0A0A", "#47107D", "#F2B01E", "#E8E6E1", "#A8A5A0"],
    mix: "Night · Deep Amethyst · Luminous Gold · Platinum · Muted Platinum",
    usage: "proposals, app, Omegea",
  },
  {
    name: "Sensory Studio",
    slug: "sensory-studio",
    colors: ["#D9531A", "#C15C27", "#E28D1F", "#E1A443", "#F7DFC0", "#0A0A0A"],
    mix: "Sunset Ember · Clay Ember · Marigold · Harvest Gold · Warm Sand · Night",
    usage: "design and creative collateral",
  },
  {
    name: "Data Alchemy",
    slug: "data-alchemy",
    colors: ["#47107D", "#F2B01E", "#D9531A", "#0D5E39", "#587156"],
    mix: "Amethyst · Gold · Ember · Rich Forest · Sage",
    usage: "5 distinct categorical series on Night or Platinum",
  },
  {
    name: "Sacred Transmission",
    slug: "sacred-transmission",
    colors: ["#042F1E", "#47107D", "#587156", "#E1A443", "#F7DFC0"],
    mix: "Midnight Forest · Deep Amethyst · Sage · Harvest Gold · Warm Sand",
    usage: "spiritual, ritual, journaling",
  },
  {
    name: "Ancestral Craft",
    slug: "ancestral-craft",
    colors: ["#B04720", "#E1A443", "#042F1E", "#F7DFC0", "#0A0A0A"],
    mix: "Terracotta · Harvest Gold · Midnight Forest · Warm Sand · Night",
    usage: "packaging, foil, embroidery",
  },
  {
    name: "Shon",
    slug: "shon",
    colors: ["#0A0A0A", "#D9531A", "#F2B01E", "#47107D", "#E8E6E1"],
    mix: "Night · Sunset Ember · Gold · Amethyst · Platinum",
    usage: "launches, provocation, manifesto",
  },
  {
    name: "Master Avatar",
    slug: "master-avatar",
    colors: ["#0A0A0A", "#47107D", "#0D5E39", "#F2B01E", "#E8E6E1"],
    mix: "Night · Amethyst · Rich Forest · Gold · Platinum",
    usage: "the complete UJG signature",
  },
  {
    name: "Afro-Futurist Royal",
    slug: "afro-futurist-royal",
    colors: ["#0A0A0A", "#47107D", "#F2B01E", "#B04720"],
    mix: "Night · Amethyst · Gold · Terracotta",
    usage: "main brand visuals, premium proposals",
  },
  {
    name: "Urban Jungle Grounded",
    slug: "urban-jungle-grounded",
    colors: ["#042F1E", "#0D5E39", "#587156", "#F7DFC0", "#E8E6E1"],
    mix: "Midnight Forest · Rich Forest · Sage · Warm Sand · Platinum",
    usage: "wellness, sustainability",
  },
  {
    name: "Warm Neutral",
    slug: "warm-neutral",
    colors: ["#F7DFC0", "#E1A443", "#B04720", "#587156", "#0A0A0A"],
    mix: "Warm Sand · Harvest Gold · Terracotta · Sage · Night",
    usage: "long-form, blog, print editorial",
  },
  {
    name: "Launch Heat",
    slug: "launch-heat",
    colors: ["#0A0A0A", "#47107D", "#D9531A", "#F2B01E"],
    mix: "Night · Amethyst · Sunset Ember · Gold",
    usage: "product drops, promos, urgency",
  },
  {
    name: "Platinum Tech",
    slug: "platinum-tech",
    colors: ["#E8E6E1", "#A8A5A0", "#47107D", "#0A0A0A"],
    mix: "Platinum · Muted Platinum · Amethyst · Night",
    usage: "light-mode app, dashboards, docs",
  },
  {
    name: "Gilded Legacy",
    slug: "gilded-legacy",
    colors: ["#0A0A0A", "#F2B01E", "#E1A443", "#B04720", "#E8E6E1"],
    mix: "Night · Gold · Harvest Gold · Terracotta · Platinum",
    usage: "legacy, investment, premium tiers",
  },
  {
    name: "Ritual Grove",
    slug: "ritual-grove",
    colors: ["#042F1E", "#47107D", "#F2B01E", "#587156", "#F7DFC0"],
    mix: "Midnight Forest · Amethyst · Gold · Sage · Warm Sand",
    usage: "sacred events, retreats, invocations",
  },
  {
    name: "Signal Fire",
    slug: "signal-fire",
    colors: ["#D9531A", "#E28D1F", "#47107D", "#0A0A0A", "#E8E6E1"],
    mix: "Sunset Ember · Marigold · Amethyst · Night · Platinum",
    usage: "IG, LinkedIn, high-scroll content",
  },
  {
    name: "Deep System",
    slug: "deep-system",
    colors: ["#0A0A0A", "#0D5E39", "#47107D", "#A8A5A0"],
    mix: "Night · Rich Forest · Amethyst · Muted Platinum",
    usage: "dark-mode app, code, cyber",
  },
  {
    name: "Soft Botanical",
    slug: "soft-botanical",
    colors: ["#F7DFC0", "#587156", "#0D5E39", "#E1A443"],
    mix: "Warm Sand · Sage · Rich Forest · Harvest Gold",
    usage: "welcome flows, gentle first-touch",
  },
  {
    name: "Full Spectrum",
    slug: "full-spectrum",
    colors: ["#47107D", "#B04720", "#E1A443", "#042F1E", "#F7DFC0"],
    mix: "Amethyst · Terracotta · Harvest Gold · Midnight Forest · Warm Sand",
    usage: "portfolio, brand showcase",
  },
  {
    name: "Quiet Ground",
    slug: "quiet-ground",
    colors: ["#0A0A0A", "#587156", "#E1A443", "#F7DFC0", "#E8E6E1"],
    mix: "Night · Sage · Harvest Gold · Warm Sand · Platinum",
    usage: "meditation, quiet content, rest",
  },
] as const satisfies readonly UjgScheme[];

/** Front matter from the reference sheet, carried across verbatim. */
export const ujgMeta = {
  title: "UJG Color System v2.0",
  heading: "Urban Jungle Goddess — Color System v2.0",
  kicker: "Book 3 · The Canopy · 3B.1",
  lead: "Locked Jul 29, 2026. Six core colors, each specified across ten value systems. Math systems (HEX, RGB, CMYK, HSB, HUE, LAB) are exact. RAL, Copic, HKS, and Prismacolor are nearest physical matches — verify on a fan deck before production.",
  goldenRule: "Golden Rule — Never use more than 3 colors in a single design element.",
  note: "On the physical-match systems: HEX, RGB, CMYK, HSB, HUE, and LAB are computed exactly from each hex. RAL, Copic, HKS, and Prismacolor are ink / marker / pencil libraries with no exact digital formula — the values shown are the nearest visual match and should be confirmed against a physical fan deck before any print, signage, or illustration run. CMYK is an uncoated naive conversion; for production, soft-proof against your printer's ICC profile.",
  source: "ujg_color_system_v2_1.html",
} as const;
